export const colors = {
	primary: '#1d2b64',
	secondary: '#36d1dc',
	background: '#f4f6fb',
	surface: '#ffffff',
	border: '#e1e6ed',
	borderMuted: '#e3e8ef',
	text: '#1b2a41',
	muted: '#6c7a92',
	mutedAlt: '#8a94a6',
	accent: '#1d8cf8',
	danger: '#d22',
	badgeBackground: '#e8efff',
	placeholderSurface: '#f8fafc',
	textMuted: '#68758b',
	textSubtle: '#94a0b2',
	surfaceAlt: '#f8faff',
	surfaceRaised: '#ffffff',
	borderStrong: '#cbd5e2',
	white: '#ffffff',
	success: '#16835c',
	warning: '#ad690f',
	dangerSoft: '#fff0ef',
	successSoft: '#e8f7ef',
	warningSoft: '#fff4df',
	infoSoft: '#e9f7fa',
	primarySoft: '#ebeffb',
	statusSubmitted: '#eaf0ff',
	statusInProgress: '#e8f7fa',
	statusImplemented: '#e8f7ef',
	statusToVerify: '#fff4df',
	statusCancelled: '#fff0ef',
	statusTextSubmitted: '#3456a4',
	statusTextInProgress: '#147d8a',
	statusTextImplemented: '#16835c',
	statusTextToVerify: '#ad690f',
	statusTextCancelled: '#b94141',
	backdrop: 'rgba(20, 32, 62, 0.42)',
	accentWash: '#36d1dc22',
	medalGold: '#e3aa35',
	medalSilver: '#8695ae',
	medalBronze: '#bf8356',
	roleLeadSurface: '#ecfeff',
	roleLeadBorder: '#a5f3fc',
	roleLeadText: '#155e75',
	roleManagerSurface: '#ede9fe',
	roleManagerBorder: '#c4b5fd',
	roleManagerText: '#5b21b6',
	roleDirectorSurface: '#fff4df',
	roleDirectorBorder: '#fde68a',
	roleDirectorText: '#ad690f',
	roleEmployeeSurface: '#dbeafe',
	roleEmployeeBorder: '#93c5fd',
	roleEmployeeText: '#1e40af',
};

export default colors;
