"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from config_kaizen.config import BASE_DIR

load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('DJANGO_SECRET')
ACCESS_SECONDS = int(os.getenv('ACCESS_TOKEN_SECONDS', 900)) # Default 5 mins
REFRESH_SECONDS = int(os.getenv('REFRESH_TOKEN_SECONDS', 86400))
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'

CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURITY WARNING: don't run with debug turned on in production
DEBUG = True

MEDIA_URL = '/kaizen_attachments/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', 20 * 1024 * 1024))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 20 * 1024 * 1024))

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if host.strip()]
if DEBUG:
    ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users',
    'ideas',
    'drf_spectacular',
    'django_extensions',
    'rest_framework_simplejwt.token_blacklist',
    'access_control',
    'app',
]

REST_FRAMEWORK = {
    # DRF, Spectacular do schematu
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=ACCESS_SECONDS),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=REFRESH_SECONDS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JAZZMIN_SETTINGS = {
    "site_title": "Kaizen Admin",
    "site_header": "Kaizen",
    "site_brand": "Admin Dashboard",
    # Login Page Logo
    "site_logo": "admin/img/logo.png",
    "site_logo_classes": "img-fluid img-circle",
    # Sidebar Logo (Dashboard)
    "site_brand_logo": "admin/img/logo.png",
    # Favicon
    "site_icon": "admin/img/logo.png",
    "welcome_sign": "Welcome to the Kaizen App Management Portal",
    "copyright": "Upcoders sp. z o.o",
    "search_model": [
        "ideas.KaizenPost",   # Searches "Posty"
        "ideas.PostSurvey",   # Searches "Ankiety do postów"
        "users.CustomUser",   # Searches "Użytkownicy"
        "ideas.Notification", # Searches "Powiadomienia"
    ],
    "custom_css": "admin/css/custom_admin.css",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "users.CustomUser": "fas fa-user-friends",  # Użytkownicy
        "ideas.KaizenPost": "fas fa-lightbulb",     # Posty
        "ideas.PostSurvey": "fas fa-poll-h",        # Ankiety do postów
        "ideas.Category": "fas fa-folder-open",     # Kategorie
        "ideas.Notification": "fas fa-bell",        # Powiadomienia
        "ideas.Comment": "fas fa-comments",         # Komentarze
        "ideas.Like": "fas fa-thumbs-up",           # Polubienia
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",          # Modern dark theme
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary", # Uses a "Kaizen Green" for the brand
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary", # Matching green accents for sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "show_ui_builder": True,
    "button_classes": {
            "primary": "btn-primary",          # Standard Bootstrap Blue
            "success": "btn-info",             # Secondary Blue-ish tone
    }
}

# CORS (development)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'Kaizen API',
    'DESCRIPTION': 'Backend dla aplikacji zgłaszania pomysłów Kaizen',
    'VERSION': '1.0.0',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# points to a new user's model
AUTH_USER_MODEL = 'users.CustomUser'

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # PoC SQLite3, później PostgreSQL
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(Path(__file__).resolve().parents[1], "static"),
]
