# Generated by Django 6.0 on 2026-05-15 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='award', max_length=40)),
                ('criteria_type', models.CharField(choices=[('POST_COUNT', 'Liczba pomysłów'), ('LIKES_RECEIVED', 'Otrzymane lajki'), ('IMPLEMENTED_COUNT', 'Wdrożone pomysły'), ('REVIEW_COUNT', 'Wykonane weryfikacje'), ('STREAK', 'Passa dni'), ('POINTS', 'Łączne punkty'), ('COMMENT_COUNT', 'Liczba komentarzy')], max_length=32)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('tier', models.CharField(choices=[('BRONZE', 'Brąz'), ('SILVER', 'Srebro'), ('GOLD', 'Złoto')], default='BRONZE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Odznaka',
                'verbose_name_plural': 'Odznaki',
                'ordering': ['order', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('min_points', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#1d2b64', max_length=9)),
                ('icon', models.CharField(default='star', max_length=40)),
            ],
            options={
                'verbose_name': 'Poziom',
                'verbose_name_plural': 'Poziomy',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IDEA_CREATED', 'Zgłoszenie pomysłu'), ('IDEA_APPROVED', 'Pomysł zatwierdzony'), ('IDEA_IMPLEMENTED', 'Pomysł wdrożony'), ('LIKE_RECEIVED', 'Otrzymany lajk'), ('COMMENT_MADE', 'Dodany komentarz'), ('REVIEW_COMPLETED', 'Wykonana weryfikacja'), ('REWARD_REDEEMED', 'Wymiana nagrody')], max_length=32, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('daily_cap', models.PositiveIntegerField(blank=True, help_text='Maks. liczba naliczeń tej akcji dziennie (puste = bez limitu).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Reguła punktowa',
                'verbose_name_plural': 'Reguły punktowe',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cost_points', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Puste = nielimitowane.', null=True)),
                ('icon', models.CharField(default='gift', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nagroda',
                'verbose_name_plural': 'Nagrody',
                'ordering': ['order', 'cost_points'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('APPROVED', 'Zaakceptowana'), ('DELIVERED', 'Wydana'), ('REJECTED', 'Odrzucona')], default='PENDING', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='gamification.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wymiana nagrody',
                'verbose_name_plural': 'Wymiany nagród',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IDEA_CREATED', 'Zgłoszenie pomysłu'), ('IDEA_APPROVED', 'Pomysł zatwierdzony'), ('IDEA_IMPLEMENTED', 'Pomysł wdrożony'), ('LIKE_RECEIVED', 'Otrzymany lajk'), ('COMMENT_MADE', 'Dodany komentarz'), ('REVIEW_COMPLETED', 'Wykonana weryfikacja'), ('REWARD_REDEEMED', 'Wymiana nagrody')], max_length=32)),
                ('points', models.IntegerField()),
                ('dedupe_key', models.CharField(blank=True, default='', help_text='Zapobiega podwójnemu naliczeniu tej samej akcji.', max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transakcja punktowa',
                'verbose_name_plural': 'Transakcje punktowe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_d3e19d_idx'), models.Index(fields=['action', 'created_at'], name='gamificatio_action_c90b60_idx'), models.Index(fields=['created_at'], name='gamificatio_created_3e09c6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'action', 'dedupe_key'), name='uniq_user_action_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przyznana odznaka',
                'verbose_name_plural': 'Przyznane odznaki',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil gamifikacji',
                'verbose_name_plural': 'Profile gamifikacji',
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['-total_points'], name='gamificatio_total_p_391e9f_idx')],
            },
        ),
    ]
