# Generated by Django 6.0 on 2026-09-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrule',
            name='action',
            field=models.CharField(choices=[('IDEA_CREATED', 'Zgłoszenie pomysłu'), ('IDEA_APPROVED', 'Pomysł zatwierdzony'), ('IDEA_IMPLEMENTED', 'Pomysł wdrożony'), ('LIKE_RECEIVED', 'Otrzymany lajk'), ('COMMENT_MADE', 'Dodany komentarz'), ('REVIEW_COMPLETED', 'Wykonana weryfikacja'), ('REWARD_REDEEMED', 'Wymiana nagrody'), ('MANUAL_ADJUSTMENT', 'Korekta ręczna')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='action',
            field=models.CharField(choices=[('IDEA_CREATED', 'Zgłoszenie pomysłu'), ('IDEA_APPROVED', 'Pomysł zatwierdzony'), ('IDEA_IMPLEMENTED', 'Pomysł wdrożony'), ('LIKE_RECEIVED', 'Otrzymany lajk'), ('COMMENT_MADE', 'Dodany komentarz'), ('REVIEW_COMPLETED', 'Wykonana weryfikacja'), ('REWARD_REDEEMED', 'Wymiana nagrody'), ('MANUAL_ADJUSTMENT', 'Korekta ręczna')], max_length=32),
        ),
    ]
