# Generated by Django 6.0 on 2026-02-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Pracownik'), ('MANAGER', 'Kierownik')], default='EMPLOYEE', max_length=20, verbose_name='Rola'),
        ),
    ]
