# Generated by Django 6.0 on 2026-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Pracownik'), ('TEAM_LEAD', 'Lider zespołu'), ('MANAGER', 'Kierownik'), ('DIRECTOR', 'Dyrektor')], default='EMPLOYEE', max_length=20, verbose_name='Rola'),
        ),
    ]
