# Generated by Django 6.0 on 2026-05-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa działu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywny?')),
            ],
            options={
                'verbose_name': 'Dział',
                'verbose_name_plural': 'Działy',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.department', verbose_name='Dział'),
        ),
    ]
