# Generated by Django 6.0 on 2026-09-26 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_department_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Lider zespołu akceptujący pomysły pracowników działu (pierwszy etap).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL, verbose_name='Lider działu'),
        ),
    ]
