# Generated by Django 6.0 on 2025-12-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='kaizenpost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Polubienie', 'verbose_name_plural': 'Polubienia'},
        ),
    ]
