# Generated by Django 6.0 on 2025-12-29 17:28

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate_data(apps, schema_editor):
    Category = apps.get_model('ideas', 'Category')
    KaizenPost = apps.get_model('ideas', 'KaizenPost')

    # Tworzymy domyślne kategorie
    bhp, _ = Category.objects.get_or_create(name='BHP', is_active=True)
    proces, _ = Category.objects.get_or_create(name='Usprawnienie Procesu', is_active=True)
    jakosc, _ = Category.objects.get_or_create(name='Jakość', is_active=True)
    inne, _ = Category.objects.get_or_create(name='Inne', is_active=True)

    # Mapujemy stare wartości tekstowe na ID nowych obiektów
    # To zapobiegnie błędowi IntegrityError (np. 'JAKOSC' -> ID kategorii Jakość)
    mapping = {
        'BHP': bhp.id,
        'PROCES': proces.id,
        'JAKOSC': jakosc.id,
        'INNE': inne.id,
    }

    for old_val, new_id in mapping.items():
        # Aktualizujemy posty, które mają stary tekst w polu category
        KaizenPost.objects.filter(category=old_val).update(category=new_id)

    # Dla wszystkich innych, które nie pasują, ustawiamy 'Inne'
    KaizenPost.objects.exclude(category__in=[str(v) for v in mapping.values()]).update(category=inne.id)


class Migration(migrations.Migration):
    dependencies = [
        ('ideas', '0004_notification'),
    ]

    operations = [
        # Tworzymy model Category
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywna?')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),

        # Uruchamiamy funkcję tworzącą dane i naprawiającą stare wpisy
        migrations.RunPython(create_categories_and_migrate_data),

        # Operacje na indeksach (z Twojego pliku)
        migrations.RenameIndex(
            model_name='notification',
            new_name='ideas_notif_recipie_4d1569_idx',
            old_name='ideas_notif_rec_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='ideas_notif_recipie_e55bea_idx',
            old_name='ideas_notif_rec_created_idx',
        ),

        # Zmieniamy typ pola category na ForeignKey
        migrations.AlterField(
            model_name='kaizenpost',
            name='category',
            field=models.ForeignKey(
                limit_choices_to={'is_active': True},
                on_delete=django.db.models.deletion.PROTECT,
                to='ideas.category',
                verbose_name='Kategoria'
            ),
        ),
    ]