# Generated by Django 6.0 on 2026-02-09 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizenpost',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_posts', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany kierownik'),
        ),
        migrations.AddField(
            model_name='kaizenpost',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Powód odrzucenia'),
        ),
        migrations.AlterField(
            model_name='kaizenpost',
            name='status',
            field=models.CharField(choices=[('TO_VERIFY', 'Do weryfikacji'), ('SUBMITTED', 'Zgłoszony'), ('IN_PROGRESS', 'W trakcie wdrożenia'), ('IMPLEMENTED', 'Wdrożone'), ('CANCELLED', 'Odrzucony')], default='TO_VERIFY', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('APPROVED', 'Post approved'), ('REJECTED', 'Post rejected'), ('ASSIGNED', 'Assigned for review')], max_length=20),
        ),
    ]
