# Generated by Django 6.0 on 2026-05-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_kaizenpost_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ideas.comment', verbose_name='Odpowiedź na'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('REPLY', 'Reply to comment'), ('MENTION', 'Mention'), ('APPROVED', 'Post approved'), ('REJECTED', 'Post rejected'), ('ASSIGNED', 'Assigned for review')], max_length=20),
        ),
    ]
