# Generated by Django 6.0 on 2026-05-13 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizenpost',
            name='assigned_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_posts', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany dyrektor'),
        ),
        migrations.AddField(
            model_name='kaizenpost',
            name='assigned_team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead_posts', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany lider zespołu'),
        ),
        migrations.AddField(
            model_name='kaizenpost',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Termin wdrożenia'),
        ),
        migrations.AddField(
            model_name='kaizenpost',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Szacowany koszt wdrożenia (zł)'),
        ),
        migrations.AddField(
            model_name='kaizenpost',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Postęp wdrożenia (%)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'Załącznik'), ('BEFORE', 'Przed wdrożeniem'), ('AFTER', 'Po wdrożeniu')], default='GENERAL', max_length=10, verbose_name='Typ zdjęcia'),
        ),
        migrations.CreateModel(
            name='PostApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('TEAM_LEAD', 'Lider zespołu'), ('MANAGER', 'Kierownik'), ('DIRECTOR', 'Dyrektor')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('decision', models.CharField(choices=[('PENDING', 'Oczekuje'), ('APPROVED', 'Zaakceptowane'), ('REJECTED', 'Odrzucone'), ('SKIPPED', 'Pominięte')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_approvals', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ideas.kaizenpost')),
            ],
            options={
                'verbose_name': 'Etap akceptacji',
                'verbose_name_plural': 'Etapy akceptacji',
                'ordering': ['order'],
                'unique_together': {('post', 'stage')},
            },
        ),
    ]
